name: Build macOS App and Publish to GitHub Releases

on:
  push:
    branches:
     - main
jobs:
  build-macos:
    runs-on: macos-latest

    # 显式声明权限，确保有权限创建 release 和上传资产
    permissions:
      contents: write  # 允许发布 release 和上传资产
      packages: write  # 如果需要发布到 GitHub Packages

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 替换为你的 Python 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4. 打包 Python 应用
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py

      # 5. 上传构建结果（可选）
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-mac-app
          path: dist/
