# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build macOS App

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4. 打包 Python 应用
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py

      # 5. 创建 GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref | split('refs/tags/', '') }}  # 提取标签名（如 v1.0.0）
          release_name: Release ${{ github.ref | split('refs/tags/', '') }}
          body: Automated release for macOS app
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. 上传 Release 资产
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/main.app
          asset_name: main.app
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
